version: '3.7'

services:
  solarrs485mqtt:
    image: revenberg/solarrs485mqtt
    container_name: solar2mqtt
    environment:
      - RS485_ADDRESS=192.168.2.40
      - RS485_PORT=8899
      - MQTT_ADDRESS=192.168.2.80
      - MQTT_PORT=1883
      - MQTT_TOPIC=reading/solar
      - LOGGING=true
    restart: always
    depends_on:
      - solarmqtt
    links:
      - solarmqtt

  solarmqtt:
    image: "eclipse-mosquitto:latest"
    container_name: solarmqtt
    environment:
      - TZ=Europe/Amsterdam
      - "MQTT_BROKER_URL=mqtt://127.0.0.1"
    ports:
      - 1883:1883
      - 9001:9001
    user: "1000:1000"
    volumes:
      - /var/docker-compose/data/mqtt/config:/mosquitto/config
      - /var/docker-compose/data/mqtt/data:/mosquitto/data
      - /var/docker-compose/data/mqtt/log:/mosquitto/log
    restart: always
    network_mode: host
